# Generated by Django 5.2.11 on 2026-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя компании')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Штат/Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address_line', models.CharField(max_length=50, verbose_name='Домашний аддресс')),
                ('street_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Доп аддресс')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-created_at'],
            },
        ),
    ]
