# Generated by Django 5.2.11 on 2026-02-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Короткая ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Цена')),
                ('status', models.CharField(blank=True, choices=[('sold', 'Sold'), ('new', 'New'), ('sale', 'Sale')], null=True, verbose_name='Статус')),
                ('quantity', models.SmallIntegerField(default=7, verbose_name='Кол-во')),
                ('sale_percent', models.SmallIntegerField(default=0, help_text='данное поле, заполняем если статут sale', verbose_name='Процент скидки')),
                ('preview', models.ImageField(upload_to='products/previews/', verbose_name='Заставка')),
                ('categories', models.ManyToManyField(null=True, related_name='products', to='shop.category', verbose_name='категории')),
                ('tags', models.ManyToManyField(null=True, related_name='products', to='shop.tags', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
