# Generated by Django 5.2.11 on 2026-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_percent',
            field=models.SmallIntegerField(default=0, help_text='данное поле заполняем если статус sale', verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('new', 'New'), ('sale', 'Sale')], max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.tags', verbose_name='теги'),
        ),
    ]
